version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: riho-admin-app
    container_name: riho-admin-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www:delegated
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - db
    user: "${UID}:${GID}"  # Añadir esta línea para usar el usuario correcto

  db:
    image: mysql:8.0
    container_name: riho-admin-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3330:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  web:
    image: nginx:alpine
    container_name: riho-admin-web
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - .:/var/www:delegated
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local